import Head from 'next/head'
import Link from 'next/link'
import { Container, Grid, Text } from '@nextui-org/react'
import Image from 'next/image'
import fs from 'fs/promises'

import { Header } from '../components/Header'

export default function Home({ latestComics }) {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main>
        <Text h2 weight={'bold'} css={{ textAlign: 'center' }}>
          Latest Comics
        </Text>
        <Grid.Container gap={2} span={6}>
          {latestComics.map((comic) => {
            return (
              <Grid key={comic.id} css={{ margin: 'auto' }}>
                <Link href={`/comic/${comic.id}`}>
                  <Container
                    css={{
                      margin: 'auto',
                      display: 'grid',
                      placeItems: 'center',
                      height: ' 500px',
                      gap: 2
                    }}
                  >
                    <Text
                      weight={'semibold'}
                      size={'$lg'}
                      css={{ textAlign: 'center' }}
                    >
                      {comic.title}
                    </Text>
                    <Container
                      css={{
                        display: 'grid',
                        gridTemplateColumns: '1fr 1fr',
                        placeItems: 'center',
                        textAlign: 'center',
                        height: '500px'
                      }}
                    >
                      <Image
                        src={comic.img}
                        alt={comic.alt}
                        width={300}
                        height={300}
                        layout="intrinsic"
                        objectFit="contain"
                        style={{
                          maxHeight: '100%',
                          maxWidth: '100%',
                          gridColumn: '1 / span 2',
                          justifySelf: 'center'
                        }}
                      />
                    </Container>
                  </Container>
                </Link>
              </Grid>
            )
          })}
        </Grid.Container>
      </main>
    </div>
  )
}

export async function getStaticProps(context) {
  const files = await fs.readdir('./comics')
  const latestComicsFiles = files.slice(-8, files.length)

  const promisesReadFiles = latestComicsFiles.map(async (file) => {
    const content = await fs.readFile(`./comics/${file}`, 'utf8')
    return JSON.parse(content)
  })

  const latestComics = await Promise.all(promisesReadFiles)

  return {
    props: {
      latestComics
    }
  }
}
